Repository tricia-holmes/rancid-tomatillos, pull requests merged in 2022-12, with the labels that each got.

#2 Fetch Request
  src/App.js
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/App/App.test.js
  src/components/Banner/Banner.css
  src/components/Banner/Banner.jsx
  src/components/Banner/Banner.test.js
  src/components/Movie/Movie.css
  src/components/Movie/Movie.jsx
  src/components/Movie/Movie.test.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.jsx
  src/components/MovieDetails/MovieDetails.test.js
  src/components/Movies/Movies.css
  src/components/Movies/Movies.jsx
  src/components/Movies/Movies.test.js
  src/index.js
  src/logo.svg
Labels: fix

#9 Add movie details modal
  src/components/App/App.jsx
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.jsx
Labels: enhancement

#18 Create dynamic movie details for each Movie Details Route
  src/components/App/App.jsx
  src/components/MovieDetails/MovieDetails.jsx
  src/components/Movies/Movies.jsx
Labels: enhancement

#21 Dani/feature/prop types
  package-lock.json
  package.json
  src/components/App/App.jsx
  src/components/Banner/Banner.css
  src/components/Banner/Banner.jsx
  src/components/Movie/Movie.jsx
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.jsx
  src/components/Movies/Movies.jsx
Labels: enhancement

#25 e2e testing continued..
  cypress/e2e/500_error_spec.cy.js
  cypress/e2e/home_spec.cy.js
  cypress/e2e/movie_details_spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/movie_data.json
Labels: testing

#38 Tricia/style/movie details
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/Error/Error.css
  src/components/Home/Home.css
  src/components/Home/Home.jsx
  src/components/Loader/Loader.css
  src/components/Loader/Loader.jsx
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/Util/ApiCalls.js
Labels: enhancement, refactor, stying

#41 Tricia/refactor/should load
  src/components/App/App.jsx
  src/components/App/App.test.js
  src/components/Banner/Banner.test.js
  src/components/Error/Error.test.js
  src/components/Home/Home.jsx
  src/components/Movie/Movie.test.js
  src/components/MovieDetails/MovieDetails.jsx
  src/components/MovieDetails/MovieDetails.test.js
  src/components/Movies/Movies.test.js
Labels: refactor

#46 Add props for the added home and search bar components
  src/components/Home/Home.jsx
  src/components/SearchBar/SearchBar.jsx
Labels: enhancement

#47 Tricia/feature/route undefined urls
  src/components/App/App.jsx
  src/components/MovieDetails/MovieDetails.css
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.jsx
  src/components/assets/fonts/GeomatrixBold-6YBZ1.ttf
Labels: enhancement, stying

#50 Tricia/testing/stubs
  cypress/e2e/404_error_spec.cy.js
  cypress/e2e/500_error_spec.cy.js
  cypress/e2e/home_spec.cy.js
  cypress/e2e/movie_details_spec.cy.js
  cypress/e2e/test_helper.js
  cypress/fixtures/movie_data.json
  cypress/fixtures/movie_details_505642.json
  cypress/fixtures/movie_details_566466.json
  cypress/fixtures/movie_details_632856.json
  cypress/fixtures/movie_details_820067.json
  cypress/fixtures/movie_details_830784.json
  cypress/fixtures/movie_details_877269.json
  cypress/fixtures/movie_details_900667.json
  cypress/fixtures/movie_details_data.json
Labels: testing

#54 Add styling to browser tab
  public/favicon.ico
  public/index.html
Labels: stying
